version: '3'

services:
  web1:
    build: 
      context: ./web1
      dockerfile: dockerfile
    ports:
      - 8080:80
    volumes:
      - ./web1:/usr/share/nginx/html

  web2:
    build: 
      context: ./web2
      dockerfile: Dockerfile
    ports:
      - 8081:80
    volumes:
      - ./web2:/usr/share/nginx/html  