version: '3'

services:
  web1:
    build: 
      context: ./web1
      dockerfile: dockerfile
    volumes:
      - ./web1:/usr/share/nginx/html

  web2:
    build: 
      context: ./web2
      dockerfile: Dockerfile
    volumes:
      - ./web2:/usr/share/nginx/html  

  reverse-proxy:
    build:
      context: ./reverse-proxy
      dockerfile: dockerfile.proxy
    ports:
      - 80:80
    