version: '3'

services:
  db:
    build:
      context: ./DB
      dockerfile: dockerfile
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: demo_db
  
  controler:
    image: dpage/pgadmin4:latest
    ports:
      - 80:80
    environment:
      - PGADMIN_DEFAULT_EMAIL=demo@exanple.com
      - PGADMIN_DEFAULT_PASSWORD=demo
    depends_on:
      - db